### ISSUE TITLE
Generate "start of line" TTL

### ISSUE THREAD

**Issue by pbl007** [danionella/lsmaq#9]
Hi,
is it possible to output a TTL for the beginning of each line?
Thanks in advance,
Pablo

**Comment by bjudkewitz** [comment]
It is very likely possible to add some nidaqmx code to output a digital signal, if you are familiar with nidaqmx counters. Alternatively, you might be able to simply use the analog x-galvo output signal for synchronization of your hardware. Yet another option is to use the analog Pockels cell output (also called "blank" output) signal.

**Comment by pbl007** [comment]
Thanks for the tip! I know the nidaqmx counters but have never interfaced directly through code (will it be possible for to give a hint as where in the code-base one should add such line? The idea of using the blank output signal is pretty cool, is it a TTL or an analog signal to control the Pockels cell input voltage? 
Using the x-galvo signal is somehow more problematic as it changes in amplitude with zoom factor making it more difficult to simply threshold. I guess a separate circuit could be used for that but I am trying to avoid such customization right now.

**Comment by bjudkewitz** [comment]
You'd have to understand rigClass.m and the rig settings it receives (see defaultconfig.m). Then you could probably add a digital writer in rigclass.m. 
Alternatively, using the pockels output would be easier, but it is set up as an analog signal, so you'd need a spare analog channel. If you have one, you'd need to set it up in rigprops.AOchans (e.g. {'/Dev1/ao0:2'}) and set rigprops.channelOrder to something like [1 2 4] to output the pockels ("blank") signal to the third channel. Check the comments in defaultconfig.m

**Comment by bjudkewitz** [comment]
Hang on, I might be confused. Seems like digital output of the blanking signal has already been added (see GateTask in rigClass.m and rigprops.gateline in defaultconfig). So what you are looking for might already work out of the box. I don't have time to confirm it, but you could hook up sth to the port specified in rigprops.gateline and check!

**Comment by pbl007** [comment]
THANKS A LOT!!! if indeed already implemented it could be a huge help.
